import boto3
import json
import random
import time
import uuid
from datetime import datetime, timezone

sqs = boto3.client('sqs', region_name='us-east-2')
QUEUE_URL = 'https://sqs.us-east-2.amazonaws.com/611723957783/ids-events'

# Statistical profiles based on CICIDS data distributions
ATTACK_PROFILES = {
    'BENIGN': {
        'Destination Port': lambda: random.choice([80, 443, 22, 53, 8080]),
        'Flow Duration': lambda: random.randint(100000, 5000000),
        'Total Fwd Packets': lambda: random.randint(5, 50),
        'Total Backward Packets': lambda: random.randint(3, 40),
        'Total Length of Fwd Packets': lambda: random.randint(100, 5000),
        'Total Length of Bwd Packets': lambda: random.randint(500, 20000),
        'Fwd Packet Length Max': lambda: random.randint(100, 1500),
        'Fwd Packet Length Min': lambda: random.randint(0, 50),
        'Fwd Packet Length Mean': lambda: random.uniform(50, 800),
        'Fwd Packet Length Std': lambda: random.uniform(10, 200),
        'Bwd Packet Length Max': lambda: random.randint(200, 5000),
        'Bwd Packet Length Min': lambda: random.randint(0, 50),
        'Bwd Packet Length Mean': lambda: random.uniform(100, 2000),
        'Bwd Packet Length Std': lambda: random.uniform(20, 500),
        'Flow IAT Mean': lambda: random.uniform(10000, 500000),
        'Flow IAT Std': lambda: random.uniform(5000, 200000),
        'Flow IAT Max': lambda: random.randint(100000, 2000000),
        'Flow IAT Min': lambda: random.randint(1, 1000),
        'Fwd IAT Total': lambda: random.randint(50000, 2000000),
        'Fwd IAT Mean': lambda: random.uniform(10000, 400000),
        'Fwd IAT Std': lambda: random.uniform(5000, 150000),
        'Fwd IAT Max': lambda: random.randint(50000, 1500000),
        'Fwd IAT Min': lambda: random.randint(1, 500),
        'Bwd IAT Total': lambda: random.randint(50000, 2000000),
        'Bwd IAT Mean': lambda: random.uniform(10000, 400000),
        'Bwd IAT Std': lambda: random.uniform(5000, 150000),
        'Bwd IAT Max': lambda: random.randint(50000, 1500000),
        'Bwd IAT Min': lambda: random.randint(1, 500),
        'Fwd PSH Flags': lambda: random.randint(0, 1),
        'Bwd PSH Flags': lambda: 0,
        'Fwd URG Flags': lambda: 0,
        'Bwd URG Flags': lambda: 0,
        'Fwd Header Length34': lambda: random.randint(20, 200),
        'Bwd Header Length': lambda: random.randint(20, 200),
        'Fwd Packets/s': lambda: random.uniform(1, 100),
        'Bwd Packets/s': lambda: random.uniform(1, 80),
        'Min Packet Length': lambda: random.randint(0, 100),
        'Max Packet Length': lambda: random.randint(500, 5000),
        'Packet Length Mean': lambda: random.uniform(100, 1000),
        'Packet Length Std': lambda: random.uniform(50, 500),
        'Packet Length Variance': lambda: random.uniform(2500, 250000),
        'FIN Flag Count': lambda: random.randint(0, 1),
        'SYN Flag Count': lambda: random.randint(0, 1),
        'RST Flag Count': lambda: 0,
        'PSH Flag Count': lambda: random.randint(0, 1),
        'ACK Flag Count': lambda: random.randint(0, 1),
        'URG Flag Count': lambda: 0,
        'CWE Flag Count': lambda: 0,
        'ECE Flag Count': lambda: 0,
        'Down/Up Ratio': lambda: random.uniform(0.5, 3.0),
        'Average Packet Size': lambda: random.uniform(100, 1500),
        'Avg Fwd Segment Size': lambda: random.uniform(50, 800),
        'Avg Bwd Segment Size': lambda: random.uniform(100, 2000),
        'Fwd Header Length55': lambda: random.randint(20, 200),
        'Fwd Avg Bytes/Bulk': lambda: 0,
        'Fwd Avg Packets/Bulk': lambda: 0,
        'Fwd Avg Bulk Rate': lambda: 0,
        'Bwd Avg Bytes/Bulk': lambda: 0,
        'Bwd Avg Packets/Bulk': lambda: 0,
        'Bwd Avg Bulk Rate': lambda: 0,
        'Subflow Fwd Packets': lambda: random.randint(3, 40),
        'Subflow Fwd Bytes': lambda: random.randint(100, 5000),
        'Subflow Bwd Packets': lambda: random.randint(2, 30),
        'Subflow Bwd Bytes': lambda: random.randint(500, 20000),
        'Init_Win_bytes_forward': lambda: random.choice([8192, 16384, 29200, 65535]),
        'Init_Win_bytes_backward': lambda: random.choice([229, 1024, 8192, 28960]),
        'act_data_pkt_fwd': lambda: random.randint(1, 10),
        'min_seg_size_forward': lambda: random.choice([20, 24, 32]),
        'Active Mean': lambda: random.uniform(0, 50000),
        'Active Std': lambda: random.uniform(0, 10000),
        'Active Max': lambda: random.uniform(0, 100000),
        'Active Min': lambda: random.uniform(0, 10000),
        'Idle Mean': lambda: random.uniform(0, 500000),
        'Idle Std': lambda: random.uniform(0, 100000),
        'Idle Max': lambda: random.uniform(0, 1000000),
        'Idle Min': lambda: random.uniform(0, 100000),
    },
    'DDoS': {
        'Destination Port': lambda: random.choice([80, 443]),
        'Flow Duration': lambda: random.randint(500000, 2000000),
        'Total Fwd Packets': lambda: random.randint(1, 5),
        'Total Backward Packets': lambda: random.randint(3, 10),
        'Total Length of Fwd Packets': lambda: random.randint(0, 50),
        'Total Length of Bwd Packets': lambda: random.randint(5000, 15000),
        'Fwd Packet Length Max': lambda: random.randint(0, 30),
        'Fwd Packet Length Min': lambda: 0,
        'Fwd Packet Length Mean': lambda: random.uniform(0, 20),
        'Fwd Packet Length Std': lambda: random.uniform(0, 15),
        'Bwd Packet Length Max': lambda: random.randint(3000, 8000),
        'Bwd Packet Length Min': lambda: 0,
        'Bwd Packet Length Mean': lambda: random.uniform(1000, 3000),
        'Bwd Packet Length Std': lambda: random.uniform(1000, 3500),
        'Flow IAT Mean': lambda: random.uniform(50000, 300000),
        'Flow IAT Std': lambda: random.uniform(100000, 500000),
        'Flow IAT Max': lambda: random.randint(400000, 1500000),
        'Flow IAT Min': lambda: random.randint(1, 10),
        'Fwd IAT Total': lambda: random.randint(100, 20000),
        'Fwd IAT Mean': lambda: random.uniform(100, 10000),
        'Fwd IAT Std': lambda: random.uniform(0, 5000),
        'Fwd IAT Max': lambda: random.randint(100, 15000),
        'Fwd IAT Min': lambda: random.randint(1, 10),
        'Bwd IAT Total': lambda: random.randint(400000, 1500000),
        'Bwd IAT Mean': lambda: random.uniform(100000, 400000),
        'Bwd IAT Std': lambda: random.uniform(200000, 600000),
        'Bwd IAT Max': lambda: random.randint(400000, 1500000),
        'Bwd IAT Min': lambda: random.randint(1, 500),
        'Fwd PSH Flags': lambda: 0,
        'Bwd PSH Flags': lambda: 0,
        'Fwd URG Flags': lambda: 0,
        'Bwd URG Flags': lambda: 0,
        'Fwd Header Length34': lambda: random.randint(60, 100),
        'Bwd Header Length': lambda: random.randint(80, 180),
        'Fwd Packets/s': lambda: random.uniform(1, 10),
        'Bwd Packets/s': lambda: random.uniform(3, 15),
        'Min Packet Length': lambda: 0,
        'Max Packet Length': lambda: random.randint(4000, 8000),
        'Packet Length Mean': lambda: random.uniform(800, 1800),
        'Packet Length Std': lambda: random.uniform(1500, 3000),
        'Packet Length Variance': lambda: random.uniform(2000000, 8000000),
        'FIN Flag Count': lambda: 0,
        'SYN Flag Count': lambda: 0,
        'RST Flag Count': lambda: 0,
        'PSH Flag Count': lambda: 1,
        'ACK Flag Count': lambda: 0,
        'URG Flag Count': lambda: 0,
        'CWE Flag Count': lambda: 0,
        'ECE Flag Count': lambda: 0,
        'Down/Up Ratio': lambda: random.uniform(1, 3),
        'Average Packet Size': lambda: random.uniform(800, 2000),
        'Avg Fwd Segment Size': lambda: random.uniform(0, 20),
        'Avg Bwd Segment Size': lambda: random.uniform(1000, 3000),
        'Fwd Header Length55': lambda: random.randint(60, 100),
        'Fwd Avg Bytes/Bulk': lambda: 0,
        'Fwd Avg Packets/Bulk': lambda: 0,
        'Fwd Avg Bulk Rate': lambda: 0,
        'Bwd Avg Bytes/Bulk': lambda: 0,
        'Bwd Avg Packets/Bulk': lambda: 0,
        'Bwd Avg Bulk Rate': lambda: 0,
        'Subflow Fwd Packets': lambda: random.randint(1, 5),
        'Subflow Fwd Bytes': lambda: random.randint(0, 50),
        'Subflow Bwd Packets': lambda: random.randint(3, 10),
        'Subflow Bwd Bytes': lambda: random.randint(5000, 15000),
        'Init_Win_bytes_forward': lambda: 8192,
        'Init_Win_bytes_backward': lambda: 229,
        'act_data_pkt_fwd': lambda: random.randint(1, 3),
        'min_seg_size_forward': lambda: 20,
        'Active Mean': lambda: 0,
        'Active Std': lambda: 0,
        'Active Max': lambda: 0,
        'Active Min': lambda: 0,
        'Idle Mean': lambda: 0,
        'Idle Std': lambda: 0,
        'Idle Max': lambda: 0,
        'Idle Min': lambda: 0,
    },
    'DoS': {
        'Destination Port': lambda: random.choice([80, 443, 8080]),
        'Flow Duration': lambda: random.randint(50000000, 120000000),
        'Total Fwd Packets': lambda: random.randint(5, 15),
        'Total Backward Packets': lambda: random.randint(3, 10),
        'Total Length of Fwd Packets': lambda: random.randint(100, 500),
        'Total Length of Bwd Packets': lambda: random.randint(5000, 15000),
        'Fwd Packet Length Max': lambda: random.randint(100, 400),
        'Fwd Packet Length Min': lambda: 0,
        'Fwd Packet Length Mean': lambda: random.uniform(20, 80),
        'Fwd Packet Length Std': lambda: random.uniform(50, 150),
        'Bwd Packet Length Max': lambda: random.randint(3000, 7000),
        'Bwd Packet Length Min': lambda: 0,
        'Bwd Packet Length Mean': lambda: random.uniform(1000, 2500),
        'Bwd Packet Length Std': lambda: random.uniform(1500, 2500),
        'Flow IAT Mean': lambda: random.uniform(5000000, 15000000),
        'Flow IAT Std': lambda: random.uniform(20000000, 40000000),
        'Flow IAT Max': lambda: random.randint(80000000, 120000000),
        'Flow IAT Min': lambda: random.randint(1, 5),
        'Fwd IAT Total': lambda: random.randint(80000000, 120000000),
        'Fwd IAT Mean': lambda: random.uniform(10000000, 20000000),
        'Fwd IAT Std': lambda: random.uniform(30000000, 50000000),
        'Fwd IAT Max': lambda: random.randint(80000000, 120000000),
        'Fwd IAT Min': lambda: random.randint(1, 5),
        'Bwd IAT Total': lambda: random.randint(100000, 200000),
        'Bwd IAT Mean': lambda: random.uniform(20000, 40000),
        'Bwd IAT Std': lambda: random.uniform(40000, 80000),
        'Bwd IAT Max': lambda: random.randint(100000, 200000),
        'Bwd IAT Min': lambda: random.randint(50, 200),
        'Fwd PSH Flags': lambda: 0,
        'Bwd PSH Flags': lambda: 0,
        'Fwd URG Flags': lambda: 0,
        'Bwd URG Flags': lambda: 0,
        'Fwd Header Length34': lambda: random.randint(200, 300),
        'Bwd Header Length': lambda: random.randint(150, 250),
        'Fwd Packets/s': lambda: random.uniform(0.05, 0.2),
        'Bwd Packets/s': lambda: random.uniform(0.03, 0.15),
        'Min Packet Length': lambda: 0,
        'Max Packet Length': lambda: random.randint(3000, 7000),
        'Packet Length Mean': lambda: random.uniform(500, 1200),
        'Packet Length Std': lambda: random.uniform(1000, 2000),
        'Packet Length Variance': lambda: random.uniform(1000000, 4000000),
        'FIN Flag Count': lambda: 0,
        'SYN Flag Count': lambda: 0,
        'RST Flag Count': lambda: 0,
        'PSH Flag Count': lambda: 0,
        'ACK Flag Count': lambda: 1,
        'URG Flag Count': lambda: 0,
        'CWE Flag Count': lambda: 0,
        'ECE Flag Count': lambda: 0,
        'Down/Up Ratio': lambda: 0,
        'Average Packet Size': lambda: random.uniform(600, 1200),
        'Avg Fwd Segment Size': lambda: random.uniform(20, 80),
        'Avg Bwd Segment Size': lambda: random.uniform(1000, 2500),
        'Fwd Header Length55': lambda: random.randint(200, 300),
        'Fwd Avg Bytes/Bulk': lambda: 0,
        'Fwd Avg Packets/Bulk': lambda: 0,
        'Fwd Avg Bulk Rate': lambda: 0,
        'Bwd Avg Bytes/Bulk': lambda: 0,
        'Bwd Avg Packets/Bulk': lambda: 0,
        'Bwd Avg Bulk Rate': lambda: 0,
        'Subflow Fwd Packets': lambda: random.randint(5, 15),
        'Subflow Fwd Bytes': lambda: random.randint(100, 500),
        'Subflow Bwd Packets': lambda: random.randint(3, 10),
        'Subflow Bwd Bytes': lambda: random.randint(5000, 15000),
        'Init_Win_bytes_forward': lambda: random.choice([274, 512, 1024]),
        'Init_Win_bytes_backward': lambda: random.choice([229, 235, 512]),
        'act_data_pkt_fwd': lambda: random.randint(1, 3),
        'min_seg_size_forward': lambda: 32,
        'Active Mean': lambda: random.uniform(10000, 20000),
        'Active Std': lambda: 0,
        'Active Max': lambda: random.uniform(10000, 20000),
        'Active Min': lambda: random.uniform(10000, 20000),
        'Idle Mean': lambda: random.uniform(80000000, 120000000),
        'Idle Std': lambda: 0,
        'Idle Max': lambda: random.uniform(80000000, 120000000),
        'Idle Min': lambda: random.uniform(80000000, 120000000),
    },
    'PortScan': {
        'Destination Port': lambda: random.randint(1, 65535),
        'Flow Duration': lambda: random.randint(10, 200),
        'Total Fwd Packets': lambda: 1,
        'Total Backward Packets': lambda: 1,
        'Total Length of Fwd Packets': lambda: random.randint(0, 10),
        'Total Length of Bwd Packets': lambda: random.randint(0, 10),
        'Fwd Packet Length Max': lambda: random.randint(0, 10),
        'Fwd Packet Length Min': lambda: random.randint(0, 5),
        'Fwd Packet Length Mean': lambda: random.uniform(0, 8),
        'Fwd Packet Length Std': lambda: 0,
        'Bwd Packet Length Max': lambda: random.randint(0, 10),
        'Bwd Packet Length Min': lambda: random.randint(0, 5),
        'Bwd Packet Length Mean': lambda: random.uniform(0, 8),
        'Bwd Packet Length Std': lambda: 0,
        'Flow IAT Mean': lambda: random.uniform(10, 200),
        'Flow IAT Std': lambda: 0,
        'Flow IAT Max': lambda: random.randint(10, 200),
        'Flow IAT Min': lambda: random.randint(10, 200),
        'Fwd IAT Total': lambda: 0,
        'Fwd IAT Mean': lambda: 0,
        'Fwd IAT Std': lambda: 0,
        'Fwd IAT Max': lambda: 0,
        'Fwd IAT Min': lambda: 0,
        'Bwd IAT Total': lambda: 0,
        'Bwd IAT Mean': lambda: 0,
        'Bwd IAT Std': lambda: 0,
        'Bwd IAT Max': lambda: 0,
        'Bwd IAT Min': lambda: 0,
        'Fwd PSH Flags': lambda: 0,
        'Bwd PSH Flags': lambda: 0,
        'Fwd URG Flags': lambda: 0,
        'Bwd URG Flags': lambda: 0,
        'Fwd Header Length34': lambda: random.randint(20, 30),
        'Bwd Header Length': lambda: random.randint(18, 25),
        'Fwd Packets/s': lambda: random.uniform(5000, 50000),
        'Bwd Packets/s': lambda: random.uniform(5000, 50000),
        'Min Packet Length': lambda: random.randint(0, 5),
        'Max Packet Length': lambda: random.randint(5, 15),
        'Packet Length Mean': lambda: random.uniform(2, 8),
        'Packet Length Std': lambda: random.uniform(1, 4),
        'Packet Length Variance': lambda: random.uniform(1, 20),
        'FIN Flag Count': lambda: 0,
        'SYN Flag Count': lambda: 0,
        'RST Flag Count': lambda: 0,
        'PSH Flag Count': lambda: 1,
        'ACK Flag Count': lambda: 0,
        'URG Flag Count': lambda: 0,
        'CWE Flag Count': lambda: 0,
        'ECE Flag Count': lambda: 0,
        'Down/Up Ratio': lambda: 1,
        'Average Packet Size': lambda: random.uniform(3, 10),
        'Avg Fwd Segment Size': lambda: random.uniform(0, 5),
        'Avg Bwd Segment Size': lambda: random.uniform(3, 8),
        'Fwd Header Length55': lambda: random.randint(20, 30),
        'Fwd Avg Bytes/Bulk': lambda: 0,
        'Fwd Avg Packets/Bulk': lambda: 0,
        'Fwd Avg Bulk Rate': lambda: 0,
        'Bwd Avg Bytes/Bulk': lambda: 0,
        'Bwd Avg Packets/Bulk': lambda: 0,
        'Bwd Avg Bulk Rate': lambda: 0,
        'Subflow Fwd Packets': lambda: 1,
        'Subflow Fwd Bytes': lambda: random.randint(0, 10),
        'Subflow Bwd Packets': lambda: 1,
        'Subflow Bwd Bytes': lambda: random.randint(0, 10),
        'Init_Win_bytes_forward': lambda: random.choice([512, 1024, 2048]),
        'Init_Win_bytes_backward': lambda: 0,
        'act_data_pkt_fwd': lambda: 0,
        'min_seg_size_forward': lambda: 24,
        'Active Mean': lambda: 0,
        'Active Std': lambda: 0,
        'Active Max': lambda: 0,
        'Active Min': lambda: 0,
        'Idle Mean': lambda: 0,
        'Idle Std': lambda: 0,
        'Idle Max': lambda: 0,
        'Idle Min': lambda: 0,
    },
    'BruteForce': {
        'Destination Port': lambda: random.choice([21, 22, 3389]),
        'Flow Duration': lambda: random.randint(100, 1000),
        'Total Fwd Packets': lambda: random.randint(2, 5),
        'Total Backward Packets': lambda: random.randint(1, 3),
        'Total Length of Fwd Packets': lambda: random.randint(5, 30),
        'Total Length of Bwd Packets': lambda: 0,
        'Fwd Packet Length Max': lambda: random.randint(5, 20),
        'Fwd Packet Length Min': lambda: 0,
        'Fwd Packet Length Mean': lambda: random.uniform(3, 15),
        'Fwd Packet Length Std': lambda: random.uniform(5, 15),
        'Bwd Packet Length Max': lambda: 0,
        'Bwd Packet Length Min': lambda: 0,
        'Bwd Packet Length Mean': lambda: 0,
        'Bwd Packet Length Std': lambda: 0,
        'Flow IAT Mean': lambda: random.uniform(100, 300),
        'Flow IAT Std': lambda: random.uniform(50, 200),
        'Flow IAT Max': lambda: random.randint(200, 500),
        'Flow IAT Min': lambda: random.randint(50, 150),
        'Fwd IAT Total': lambda: random.randint(200, 800),
        'Fwd IAT Mean': lambda: random.uniform(200, 600),
        'Fwd IAT Std': lambda: 0,
        'Fwd IAT Max': lambda: random.randint(200, 800),
        'Fwd IAT Min': lambda: random.randint(200, 500),
        'Bwd IAT Total': lambda: 0,
        'Bwd IAT Mean': lambda: 0,
        'Bwd IAT Std': lambda: 0,
        'Bwd IAT Max': lambda: 0,
        'Bwd IAT Min': lambda: 0,
        'Fwd PSH Flags': lambda: 1,
        'Bwd PSH Flags': lambda: 0,
        'Fwd URG Flags': lambda: 0,
        'Bwd URG Flags': lambda: 0,
        'Fwd Header Length34': lambda: random.randint(50, 80),
        'Bwd Header Length': lambda: random.randint(15, 25),
        'Fwd Packets/s': lambda: random.uniform(3000, 8000),
        'Bwd Packets/s': lambda: random.uniform(1500, 4000),
        'Min Packet Length': lambda: 0,
        'Max Packet Length': lambda: random.randint(10, 20),
        'Packet Length Mean': lambda: random.uniform(5, 15),
        'Packet Length Std': lambda: random.uniform(5, 12),
        'Packet Length Variance': lambda: random.uniform(30, 100),
        'FIN Flag Count': lambda: 0,
        'SYN Flag Count': lambda: 1,
        'RST Flag Count': lambda: 0,
        'PSH Flag Count': lambda: 0,
        'ACK Flag Count': lambda: 1,
        'URG Flag Count': lambda: 0,
        'CWE Flag Count': lambda: 0,
        'ECE Flag Count': lambda: 0,
        'Down/Up Ratio': lambda: 0,
        'Average Packet Size': lambda: random.uniform(5, 15),
        'Avg Fwd Segment Size': lambda: random.uniform(3, 12),
        'Avg Bwd Segment Size': lambda: 0,
        'Fwd Header Length55': lambda: random.randint(50, 80),
        'Fwd Avg Bytes/Bulk': lambda: 0,
        'Fwd Avg Packets/Bulk': lambda: 0,
        'Fwd Avg Bulk Rate': lambda: 0,
        'Bwd Avg Bytes/Bulk': lambda: 0,
        'Bwd Avg Packets/Bulk': lambda: 0,
        'Bwd Avg Bulk Rate': lambda: 0,
        'Subflow Fwd Packets': lambda: random.randint(2, 5),
        'Subflow Fwd Bytes': lambda: random.randint(5, 30),
        'Subflow Bwd Packets': lambda: random.randint(1, 3),
        'Subflow Bwd Bytes': lambda: 0,
        'Init_Win_bytes_forward': lambda: random.choice([229, 512, 1024]),
        'Init_Win_bytes_backward': lambda: 0,
        'act_data_pkt_fwd': lambda: 0,
        'min_seg_size_forward': lambda: 32,
        'Active Mean': lambda: 0,
        'Active Std': lambda: 0,
        'Active Max': lambda: 0,
        'Active Min': lambda: 0,
        'Idle Mean': lambda: 0,
        'Idle Std': lambda: 0,
        'Idle Max': lambda: 0,
        'Idle Min': lambda: 0,
    },
    'WebAttack': {
        'Destination Port': lambda: 80,
        'Flow Duration': lambda: random.randint(3000000, 8000000),
        'Total Fwd Packets': lambda: random.randint(2, 5),
        'Total Backward Packets': lambda: random.randint(1, 3),
        'Total Length of Fwd Packets': lambda: 0,
        'Total Length of Bwd Packets': lambda: 0,
        'Fwd Packet Length Max': lambda: 0,
        'Fwd Packet Length Min': lambda: 0,
        'Fwd Packet Length Mean': lambda: 0,
        'Fwd Packet Length Std': lambda: 0,
        'Bwd Packet Length Max': lambda: 0,
        'Bwd Packet Length Min': lambda: 0,
        'Bwd Packet Length Mean': lambda: 0,
        'Bwd Packet Length Std': lambda: 0,
        'Flow IAT Mean': lambda: random.uniform(1000000, 3000000),
        'Flow IAT Std': lambda: random.uniform(2000000, 4000000),
        'Flow IAT Max': lambda: random.randint(4000000, 7000000),
        'Flow IAT Min': lambda: random.randint(50, 200),
        'Fwd IAT Total': lambda: random.randint(3000000, 7000000),
        'Fwd IAT Mean': lambda: random.uniform(1500000, 4000000),
        'Fwd IAT Std': lambda: random.uniform(2000000, 5000000),
        'Fwd IAT Max': lambda: random.randint(4000000, 7000000),
        'Fwd IAT Min': lambda: random.randint(500, 1000),
        'Bwd IAT Total': lambda: 0,
        'Bwd IAT Mean': lambda: 0,
        'Bwd IAT Std': lambda: 0,
        'Bwd IAT Max': lambda: 0,
        'Bwd IAT Min': lambda: 0,
        'Fwd PSH Flags': lambda: 0,
        'Bwd PSH Flags': lambda: 0,
        'Fwd URG Flags': lambda: 0,
        'Bwd URG Flags': lambda: 0,
        'Fwd Header Length34': lambda: random.randint(80, 130),
        'Bwd Header Length': lambda: random.randint(30, 50),
        'Fwd Packets/s': lambda: random.uniform(0.3, 1.0),
        'Bwd Packets/s': lambda: random.uniform(0.1, 0.4),
        'Min Packet Length': lambda: 0,
        'Max Packet Length': lambda: 0,
        'Packet Length Mean': lambda: 0,
        'Packet Length Std': lambda: 0,
        'Packet Length Variance': lambda: 0,
        'FIN Flag Count': lambda: 0,
        'SYN Flag Count': lambda: 0,
        'RST Flag Count': lambda: 0,
        'PSH Flag Count': lambda: 1,
        'ACK Flag Count': lambda: 0,
        'URG Flag Count': lambda: 0,
        'CWE Flag Count': lambda: 0,
        'ECE Flag Count': lambda: 0,
        'Down/Up Ratio': lambda: 0,
        'Average Packet Size': lambda: 0,
        'Avg Fwd Segment Size': lambda: 0,
        'Avg Bwd Segment Size': lambda: 0,
        'Fwd Header Length55': lambda: random.randint(80, 130),
        'Fwd Avg Bytes/Bulk': lambda: 0,
        'Fwd Avg Packets/Bulk': lambda: 0,
        'Fwd Avg Bulk Rate': lambda: 0,
        'Bwd Avg Bytes/Bulk': lambda: 0,
        'Bwd Avg Packets/Bulk': lambda: 0,
        'Bwd Avg Bulk Rate': lambda: 0,
        'Subflow Fwd Packets': lambda: random.randint(2, 5),
        'Subflow Fwd Bytes': lambda: 0,
        'Subflow Bwd Packets': lambda: random.randint(1, 3),
        'Subflow Bwd Bytes': lambda: 0,
        'Init_Win_bytes_forward': lambda: random.choice([29200, 28960, 16384]),
        'Init_Win_bytes_backward': lambda: random.choice([28960, 16384, 8192]),
        'act_data_pkt_fwd': lambda: 0,
        'min_seg_size_forward': lambda: 32,
        'Active Mean': lambda: 0,
        'Active Std': lambda: 0,
        'Active Max': lambda: 0,
        'Active Min': lambda: 0,
        'Idle Mean': lambda: 0,
        'Idle Std': lambda: 0,
        'Idle Max': lambda: 0,
        'Idle Min': lambda: 0,
    }
}

# Traffic mix (70% benign, 30% attacks)
TRAFFIC_MIX = {
    'BENIGN': 0.70,
    'DDoS': 0.08,
    'DoS': 0.07,
    'PortScan': 0.06,
    'BruteForce': 0.05,
    'WebAttack': 0.04,
}

def generate_event(attack_type):
    profile = ATTACK_PROFILES[attack_type]
    event = {key: float(val()) for key, val in profile.items()}
    event['event_id'] = f"{attack_type.lower()}-{uuid.uuid4().hex[:8]}"
    event['timestamp'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    return event

def send_event(event):
    sqs.send_message(
        QueueUrl=QUEUE_URL,
        MessageBody=json.dumps(event)
    )

def pick_attack_type():
    r = random.random()
    cumulative = 0
    for attack_type, prob in TRAFFIC_MIX.items():
        cumulative += prob
        if r <= cumulative:
            return attack_type
    return 'BENIGN'

def run_simulator(interval_seconds=5, burst_probability=0.1):
    print(f"Starting IDS traffic simulator...")
    print(f"Sending events every {interval_seconds} seconds")
    print(f"Traffic mix: {TRAFFIC_MIX}")
    print(f"Press Ctrl+C to stop\n")

    event_count = 0
    while True:
        # Occasionally simulate a burst attack
        if random.random() < burst_probability:
            attack_type = random.choice(['DDoS', 'PortScan', 'BruteForce'])
            burst_size = random.randint(3, 8)
            print(f"!!  BURST ATTACK: {burst_size}x {attack_type}")
            for _ in range(burst_size):
                event = generate_event(attack_type)
                send_event(event)
                event_count += 1
        else:
            attack_type = pick_attack_type()
            event = generate_event(attack_type)
            send_event(event)
            event_count += 1
            label = '.' if attack_type == 'BENIGN' else '!!'
            print(f"{label} [{event['timestamp']}] {attack_type:12} | {event['event_id']}")

        time.sleep(interval_seconds)

if __name__ == '__main__':
    run_simulator(interval_seconds=5, burst_probability=0.1)